#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed:
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman will not upgrade packages in the IgnorePkg and IgnoreGroup lists
# below. Comment out this line (or set it to the empty string) if you
# don't want to ignore any upgrades.
#IgnorePkg   =
#IgnoreGroup =

# Pacman will not upgrade packages that are listed in NoUpgrade.
# Be sure to use the full path, those listed in NoUpgrade are not matched
# against a glob() pattern.
#NoUpgrade   =

# By default, pacman accepts packages signed by keys that it knows about.
# As a safeguard, it will refuse to install unsigned packages or packages
# signed by keys it doesn't know about. Trusting an unknown key is done via
# the --init flag in pacman-key and --populate flag in pacman-key.
# NOTE: Using SigLevel=Never is not recommended and is strongly discouraged as
# it removes all checks placed in pacman to ensure package integrity. Only use
# this setting if you understand and accept the risks of unsigned packages.
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: This option only applies to the user arch-chroot'd into the system or
# using 'pacman --sysroot'. It has no effect on the host system.
# NOTE: Multi-level packages groups are not entirely supported, so -S pkg1 pkg2
# will assume pkg1 and pkg2 are in the same group. Similarly, remove identically
# named packages from different groups.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages have
#     identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository order matters; repositories listed first will take precedence
# when packages have identical names, regardless of version number.
#
# By default, this uses the [testing] repositories where your security
# system is not yet marked as stable. Uncomment only if you understand
# what you are doing.

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on how to create your own repository.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
